In [1]:
import numpy as np

### Create row and column vector

In [8]:
row_vec=np.array([[1, -5, 3, 2, 4]])
col_vec=np.array([[1], [2], [3], [4]])
print(row_vec.shape)
print(col_vec.shape)

(1, 5)
(4, 1)


### Transpose a vector

In [9]:
new_vec=row_vec.T
print(new_vec)
print(new_vec.shape)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
(5, 1)


### Norm of a vector $L_1, L_2, L_{\infty}$

In [10]:
norm1=np.linalg.norm(new_vec, 1)
norm2=np.linalg.norm(new_vec, 2)
norm_inf=np.linalg.norm(new_vec, np.inf)
print(norm1)
print(norm2)
print(norm_inf)

15.0
7.416198487095664
5.0


### Dot product

In [12]:
v=np.array([[10, 9, 3]])
w=np.array([[2, 5, 12]])
theta=np.arccos(np.dot(v, w.T)/(np.linalg.norm(v)*np.linalg.norm(w)))
print(theta)

[[0.97992471]]


### Cross product

In [13]:
v=np.array([[0, 2, 0]])
w=np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


### Linear combiantion

Given the row vectors $v = [0, 3, 2]$, $w = [4, 1, 1]$, and $u = [0,−2, 0]$, write the vector
$x = [−8,−1, 4]$ as a linear combination of $v$, $w$, and $u$.

In [14]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


### Matrix multiplication

In [16]:
P=np.array([[1, 7], [2, 3], [5, 0]])
Q=np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [17]:
print(np.dot(Q, P))

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

### Determinant of a square matrix

In [2]:
M = np.array([[0,2,1,3],
             [3,2,8,1],
             [1,0,0,3],
             [0,3,2,1]])
print("M:\n", M)

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]


In [19]:
print("Determinant: %.1f"%np.linalg.det(M))

Determinant: -38.0


### Identity matrix

In [22]:
I=np.eye(4)
print("Identity: \n", I)
print("M*I=M: \n", np.dot(M, I))

Identity: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I=M: 
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


### Inverse of matrix

In [24]:
M = np.array([[0,2,1,3],
              [3,2,8,1],
              [1,0,0,3],
              [0,3,2,1]])
print("inverse of M:\n", np.linalg.inv(M))
P = np.array([[0,1,0],
[0,0,0],
[1,0,1]])
print("det(p):\n", np.linalg.det(P))

inverse of M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(p):
 0.0


### Rank and condition for singualr
For the matrix $A = [[1, 1, 0], [0, 1, 0], [1, 0, 1]]$, compute the condition number and
rank. If $y = [[1], [2], [1]]$, get the augmented matrix $[A,y]$.

In [27]:
A=np.array([[1,1,0],
            [0,1,0],
            [1,0,1]])
print("Condition number: \n", np.linalg.cond(A))
print("Rank: \n", np.linalg.matrix_rank(A))

Condition number: 
 4.048917339522305
Rank: 
 3


In [31]:
y = np.array([[1], [2], [1]])
A_y=np.concatenate((A, y), axis=1)
print("Augmented matrix: \n", A_y)

Augmented matrix: 
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
